### ISSUE TITLE
Translations for Markdown and AsciiDOC

### ISSUE THREAD

**Issue by srbala** [argosopentech/custom-translation#1]
It would be nice to have Translations for Markdown and Asciidoc. I understand we can use `translation-html`, pre translation ie. prior to HTML would be better for review and approval can be done on translations.

**Comment by argosopentech** [comment]
I would post this on the main Argos Translate or translate-html project for visibility.

**Comment by srbala** [comment]
Moved the issue to  https://github.com/argosopentech/argos-translate/issues/215
